---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sburegjatim/
    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/customers/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/customers/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/customers/css